"""Fixing metadata and pool import

Revision ID: 624525128d30
Revises: 39b88b19b2a7
Create Date: 2025-06-08 06:01:49.361639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624525128d30'
down_revision = '39b88b19b2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
