"""debug status column detection

Revision ID: 6c149d524271
Revises: 41b0b9ec21e5
Create Date: 2025-06-08 14:41:01.480127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c149d524271'
down_revision = '41b0b9ec21e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
