"""attempt to add status column again and again

Revision ID: 9cac71294588
Revises: eccab3c44264
Create Date: 2025-06-08 14:54:09.122891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cac71294588'
down_revision = 'eccab3c44264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
