"""add status column again and again

Revision ID: c48ba9b617da
Revises: 9cac71294588
Create Date: 2025-06-08 15:00:30.241818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48ba9b617da'
down_revision = '9cac71294588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('posts', sa.Column('review_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_column('posts', 'review_notes')
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
