"""attempt to add status column again

Revision ID: eccab3c44264
Revises: 6c149d524271
Create Date: 2025-06-08 14:47:54.473014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccab3c44264'
down_revision = '6c149d524271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
